# Header
menu:
  Docs: Doc/Initialization/1-install/
  Github: https://github.com/ecomfe/edp
rss: 
github: https://github.com/ecomfe/edp

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category

# Links
links: 
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: